The close flag must be wraped in a result-channel
The "run connection loop" pipeline expects that result is a
result-channel. The calls to has-completed? and to sucess! expect that
result contain a result-channel. Otherwise these exceptions can
happen:

java.lang.ClassCastException: clojure.lang.Keyword cannot be cast to lamina.core.pipeline.ResultChannel
	at lamina.core.pipeline$poll_result.invoke(pipeline.clj:97)
	at clojure.lang.Var.invoke(Var.java:369)
	at lamina.connections$has_completed_QMARK_.invoke(connections.clj:20)
	at lamina.connections$connect_loop$fn__6026.invoke(connections.clj:59)
	at lamina.core.pipeline$handle_error.invoke(pipeline.clj:136)

java.lang.ClassCastException: clojure.lang.Keyword cannot be cast to lamina.core.pipeline.ResultChannel
	at lamina.core.pipeline$success_BANG_.invoke(pipeline.clj:88)
	at clojure.lang.Var.invoke(Var.java:369)
	at lamina.connections$connect_loop$fn__6041$fn__6042.invoke(connections.clj:77)
	at lamina.core.pipeline$start_pipeline$fn__2562$fn__2580.invoke(pipeline.clj:209)